---
title: "Network Analysis - Visualize interactions of enriched pathways"
author: "Warasinee Mujchariyakul"
output: md_document
date: "2025-04-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load R packages
```{r}
library(igraph)
library(ggraph)
library(tidyverse)
library(tidygraph)
set.seed(12345) # for reproducibility
```

## Import node and edge data 
```{r}
## SP444
all_edge_df_SP444_GSEA_KEGG <- read.table("/Users/wmujchariyak/Desktop/Strep_all_edge_SP444_GSEA_KEGG.tsv", header = TRUE)
all_node_df_SP444_GSEA_KEGG <- read.table("/Users/wmujchariyak/Desktop/Strep_all_node_SP444_GSEA_KEGG.tsv", header = TRUE)
```

## Network ananlysis to visualize interactions of enriched pathways 
```{r}
# Example for only transcriptomics (GSEA - KEGG)

# 1. Create igraph graphs from data frames
# Check: class(ig_trans_GSEA_KEGG)
ig_SP444_GSEA_KEGG <- igraph::graph_from_data_frame(d=all_edge_df_SP444_GSEA_KEGG, vertices=all_node_df_SP444_GSEA_KEGG, directed = FALSE)

# 2. Add labels to the nodes 
tg_SP444_GSEA_KEGG <- tidygraph::as_tbl_graph(ig_SP444_GSEA_KEGG) %>% 
  tidygraph::activate(nodes) %>% 
  dplyr::mutate(label=name)

# 3. Plot the network
# set seed (so that the exact same network graph is created every time)
set.seed(12345)

# 3.1 Create a graph using the 'tg' data frame with the Fruchterman-Reingold layout
plot_tg_SP444_GSEA_KEGG_3 <- tg_SP444_GSEA_KEGG %>%
  ggraph::ggraph(layout = "fr") +
  
  # Add arcs for edges with various aesthetics
  geom_edge_arc(colour = "gray50",
                lineend = "round",
                strength = .1,
                aes(edge_width = as.factor(all_edge_df_SP444_GSEA_KEGG$nb_omics_with_edge),
                    alpha = all_edge_df_SP444_GSEA_KEGG$nb_omics_with_edge)) +
  
  # Add points for nodes with size based on nb_strain_with_node and color based on gene_set_size
  ggraph::geom_node_point(size = all_node_df_SP444_GSEA_KEGG$nb_omics_with_node*1.5,
                          aes(color = as.factor(all_node_df_SP444_GSEA_KEGG$nb_omics_with_node))) + 
                          #as.factor() turn integer to categorical variables 
  
  # Add edge of nodes on the next layer (shape = 21)
  ggraph::geom_node_point(size = all_node_df_SP444_GSEA_KEGG$nb_omics_with_node*1.5, shape = 21) + 
  
  # Add text labels for nodes with various aesthetics
  geom_node_text(aes(label = name), 
                 repel = TRUE, 
                 point.padding = unit(0.2, "lines"), 
                 colour = "gray10") +
  
  # Change node color  
  scale_color_manual(values = c("#FEE090", "#D73027")) +
  
  # Adjust edge width and alpha scales (guide = control legend display)
  scale_edge_width_manual(values = c("1" = 1, "2" = 2.5), guide = "legend") +
  scale_edge_alpha(range = c(0.2, 0.5), guide = "none") + 
  
  # Set graph background color to white
  theme_graph(background = "white") +
  
  # Adjust legend position to the top
  theme(legend.position = "bottom", 
        # suppress legend title
        legend.title = element_blank()) 
```

```{r fig.height=6.5, fig.width=16}
# 3.2 View the plot 
plot_tg_SP444_GSEA_KEGG_3 # with fig.height=8, fig.width=20
```



