---
title: "Unsupervised Analyses - PCA"
author: "Warasinee Mujchariyakul"
output: html_document
date: "2025-04-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load R packages
```{r}
library(mixOmics)
library(tidyverse)
set.seed(123) # for reproducibility
```


## Import all omics
```{r}
Strep_trans_data <- read.csv("/Users/wmujchariyak/Desktop/Strep_transcriptome_data.csv", header = TRUE) %>% column_to_rownames(var = "X")
Strep_prot_data <- read.csv("/Users/wmujchariyak/Desktop/Strep_proteome_data.csv", header = TRUE) %>% column_to_rownames(var = "X")
Strep_met_GC_data <- read.csv("/Users/wmujchariyak/Desktop/Strep_metabolome_GC_data.csv", header = TRUE) %>% column_to_rownames(var = "X")
```


## Data for MixOmics 
```{r}
data <- list(Transcript = Strep_trans_data, 
             Protein = Strep_prot_data, 
             Metabolite_LC = Strep_met_GC_data)
lapply(data, dim) # check their dimensions (24 rows)


Y <- factor(rep(c("RPMI", "SERUM"), 30)) # set the response variable as the Y df
summary(Y)
```

## PCA 
```{r}
data_name <- c("Transcript", "Protein", "Metabolite_LC")
list.final.pca <- list()
plot.tune.pca <- list()
pca.cum.var <- list()

for (i in seq_along(data_name)){
  set.seed(123) # for reproducibility
  data_pca <- data[[i]]
  # Choosing number of components
  tune.pca <- tune.pca(data_pca, ncomp = 10, scale = TRUE)
  plot.tune.pca[[i]] <- tune.pca
  # Outputs cumulative proportion of variance
  pca.cum.var[[i]] <- tune.pca$cum.var       
  # Final pca 
  final.pca <- pca(data_pca, ncomp = 3, scale = TRUE)
  list.final.pca[[i]] <- final.pca
}

# Note: Results from "tune.pca" suggest that using 3 components can cover almost 50% of variation in the datasets
```

## Data visualization - Preliminary
```{r}
# Trans
plotLoadings(list.final.pca[[1]], comp = 1, method = 'mean', contrib = 'max', size.title = rel(1))
trans.pca.var <- selectVar(list.final.pca[[1]], comp = 1)$value
trans.pca.var$Rank <- rank(abs(trans.pca.var$value.var))

# Prot
plotLoadings(list.final.pca[[2]], comp = 1, method = 'mean', contrib = 'max', size.title = rel(1))
prot.ms1.pca.var <- selectVar(list.final.pca[[2]], comp = 1)$value
prot.ms1.pca.var$Rank <- rank(abs(prot.ms1.pca.var$value.var))

# Met - LC
plotLoadings(list.final.pca[[3]], comp = 1, method = 'mean', contrib = 'max', size.title = rel(1))
met.LC.pca.var <- selectVar(list.final.pca[[3]], comp = 1)$value
met.LC.pca.var$Rank <- rank(abs(met.LC.pca.var$value.var))
```

## Data visualization - Final 
```{r}
plotIndiv_pca_trans <- plotIndiv(list.final.pca[[1]], group = Y, ind.names = FALSE,
                                  legend = TRUE, ellipse = T, style = "ggplot2", size.title = rel(2.5),
                                  size.xlabel = rel(1.5), size.ylabel = rel(1.5),
                                  title = 'Transcriptome') 

plotIndiv_pca_prot <- plotIndiv(list.final.pca[[2]], group = Y, ind.names = FALSE,
                                 legend = TRUE, ellipse = T, style = "ggplot2", 
                                 size.title = rel(2.5),
                                 size.xlabel = rel(1.5), size.ylabel = rel(1.5),
                                 title = 'Proteome')

plotIndiv_pca_met_LC <- plotIndiv(list.final.pca[[3]], group = Y, ind.names = FALSE,
                                   legend = TRUE, ellipse = T, style = "ggplot2", 
                                   size.title = rel(2.5),
                                   size.xlabel = rel(1.5), size.ylabel = rel(1.5),
                                   title = 'Metabolome (GC-MS)')
```

## Save
```{r}
#pdf("/Users/wmujchariyak/Desktop/Strep_plotIndiv_pca_trans.pdf", height = 5, width = 8)
#plotIndiv_pca_trans
#dev.off()

#pdf("/Users/wmujchariyak/Desktop/Strep_plotIndiv_pca_prot.pdf", height = 5, width = 8)
#plotIndiv_pca_prot
#dev.off()

#pdf("/Users/wmujchariyak/Desktop/Strep_plotIndiv_pca_met_LC.pdf", height = 5, width = 8)
#plotIndiv_pca_met_LC
#dev.off()
```
