---
title: "ORA & GSEA"
author: "Warasinee Mujchariyakul"
output: html_document
date: "2025-04-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load R packages
```{r}
library(clusterProfiler)
library(tidyverse)

library(conflicted)
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")

set.seed(123) # for reproducibility
```

## Import all omics
```{r}
# Import all entities fold change results (all omics combined)
all_DE.df <- readRDS("/Users/wmujchariyak/Desktop/All_entity_fold_change_long_format.rds")

# Import all functional annotations 
all.annot <- readRDS("/Users/wmujchariyak/Desktop/All_funct_annot_clean_noduplicate.rda")
```

## Set parameters
```{r}
# For ORA only 
my_FDR <- 0.05 # FDR threshold (filter signif. DE genes)
my_logFC <- 1  # logFC threshold (filter signif. DE genes)

# For ORA and GSEA
annot_origin <- unique(all.annot$fterm_origin) %>% as.character() # Use all annotations
is_core_accessory <- "yes"
```

## Example for only Transcriptomics 
### ORA & GSEA 
```{r}
## Prepare Transcriptome data / K. pneumoniae
my_species <- "Klebsiella pneumoniae"
my_omics <- "Transcriptomics RG"

all_DE.res <- all_DE.df %>%
  filter(species == my_species) %>%
  filter(experiment == my_omics)

if (grepl("Metabo", my_omics)){
  my.annot <- all.annot %>%
    filter(entity_type == "metabolite")
} else {
  my.annot <- all.annot %>%
    filter(entity_type != "metabolite")
}

Trans.list.ORA <- list()
Trans.list.ORA.summary <- list()

Trans.list.GSEA <- list()
Trans.list.GSEA.summary <- list()

for (my_strain in unique(all_DE.res$strain)){
  # ORA analysis
  # prepare input data for ORA
  ORA.df <- all_DE.res %>%
    filter(is_species_core %in% is_core_accessory ) %>%
    filter(strain == my_strain) %>%
    filter(FDR < my_FDR) %>%
    filter(abs(logFC) > my_logFC) 
  
  glist.ORA <- ORA.df$entity_id
  
  # Get strain specific background gene list 
  bglist.ORA <- all_DE.res %>%
    filter(is_species_core %in% is_core_accessory) %>%
    filter(strain == my_strain) %>%
    distinct(entity_id, .keep_all = T) %>%
    .$entity_id
  
  term_to_gene.df <- my.annot %>%
    filter(fterm_origin %in% annot_origin) %>%
    filter(entity_id %in% bglist.ORA) %>%
    dplyr::select(fterm_id, entity_id) %>%
    distinct(fterm_id, entity_id) %>%
    ungroup()
  
  term_to_name.df <- my.annot %>%
    filter(fterm_origin %in% annot_origin) %>%
    filter(entity_id %in% bglist.ORA) %>%
    dplyr::select(fterm_id, fterm_name) %>%
    distinct(fterm_id, fterm_name) %>%
    ungroup()
  
  # Calculate mean/median logFC of term/path for plot
  ORA_logFC_summary <- ORA.df %>% 
    merge(., term_to_gene.df , by = "entity_id", all.x = T) %>%
    group_by(strain, fterm_id) %>%
    summarise(mean_logFC = mean(logFC), median_logFC = median(logFC)) %>%
    ungroup() %>%
    dplyr::select(-strain)
  
  ORA <- enricher(gene = glist.ORA,
                  TERM2GENE = term_to_gene.df, 
                  TERM2NAME = term_to_name.df,
                  universe = bglist.ORA,
                  qvalueCutoff = 1,
                  minGSSize = 5, 
                  maxGSSize = length(bglist.ORA)/2,
                  pvalueCutoff = 1,
                  pAdjustMethod = "fdr") 
  
  Trans.list.ORA[[my_strain]] <- ORA
  Trans.list.ORA.summary[[my_strain]]  <- ORA %>% 
    as.data.frame() %>% 
    mutate(strain = my_strain) %>%
    mutate(experiment = my_omics) %>%
    merge(., ORA_logFC_summary, by.x = "ID", by.y = "fterm_id") 
  
###############
  # GSEA analysis
  GSEA.df <- all_DE.res %>%
    filter(is_species_core %in% is_core_accessory ) %>%
    filter(strain == my_strain) %>%
    filter(experiment == my_omics) %>%
    distinct(entity_id, .keep_all = T) 
  
  glist.GSEA <- GSEA.df$logFC 
  names(glist.GSEA) <- GSEA.df$entity_id
  glist.GSEA <- sort(glist.GSEA, decreasing = T)
  
  GSEA <- GSEA(geneList = glist.GSEA, 
               TERM2GENE = term_to_gene.df,
               TERM2NAME = term_to_name.df,
               minGSSize = 5,
               maxGSSize = length(bglist.ORA)/2,
               pvalueCutoff = 1,
               pAdjustMethod = "fdr",
               nPermSimple = 100000,  # Increase the number of permutations
               eps = 0  # Allow more precise p-value estimation
               )
  
  Trans.list.GSEA[[my_strain]] <- GSEA
  Trans.list.GSEA.summary[[my_strain]]  <- GSEA %>% 
    as.data.frame() %>% 
    mutate(strain = my_strain) %>%
    mutate(experiment = my_omics) %>%
    merge(., term_to_name.df, by.x = "ID", by.y = "fterm_id", all.x = T) 
}

```

### Check ORA and GSEA Results
```{r}
head(Trans.list.ORA.summary[["AJ218"]], 5)
head(Trans.list.GSEA.summary[["KPC2"]], 5)
```


## For loop - ORA & GSEA analysis (All omics and all strains)
```{r}
# List of omics experiments
omics_list <- c("Transcriptomics RG", "Proteomics MS1 DDA", "Metabolomics GC-MS")

# Initialize lists to store results
results_list <- list()

# Loop through omics types
for (my_omics in omics_list) {
  
  cat("\nProcessing Omics Experiment:", my_omics, "\n")
  
  # Prepare data for the current omics
  my_species <- "Klebsiella pneumoniae"
  
  all_DE.res <- all_DE.df %>%
    filter(species == my_species) %>%
    filter(experiment == my_omics)
  
  # Filter annotation based on metabolite or non-metabolite
  if (grepl("Metabo", my_omics)) {
    my.annot <- all.annot %>%
      filter(entity_type == "metabolite")
  } else {
    my.annot <- all.annot %>%
      filter(entity_type != "metabolite")
  }
  
  # Initialize lists for ORA and GSEA results
  omics_list_ORA <- list()
  omics_list_ORA_summary <- list()
  
  omics_list_GSEA <- list()
  omics_list_GSEA_summary <- list()
  
  # Iterate over strains within the current omics experiment
  for (my_strain in unique(all_DE.res$strain)) {
    
    # ORA Analysis
    ORA.df <- all_DE.res %>%
      filter(is_species_core %in% is_core_accessory) %>%
      filter(strain == my_strain) %>%
      filter(FDR < my_FDR) %>%
      filter(abs(logFC) > my_logFC)
    
    glist.ORA <- ORA.df$entity_id
    
    # Background gene list
    bglist.ORA <- all_DE.res %>%
      filter(is_species_core %in% is_core_accessory) %>%
      filter(strain == my_strain) %>%
      distinct(entity_id, .keep_all = TRUE) %>%
      .$entity_id
    
    # Prepare term-to-gene and term-to-name mappings
    term_to_gene.df <- my.annot %>%
      filter(fterm_origin %in% annot_origin) %>%
      filter(entity_id %in% bglist.ORA) %>%
      dplyr::select(fterm_id, entity_id) %>%
      distinct(fterm_id, entity_id) %>%
      ungroup()
    
    term_to_name.df <- my.annot %>%
      filter(fterm_origin %in% annot_origin) %>%
      filter(entity_id %in% bglist.ORA) %>%
      dplyr::select(fterm_id, fterm_name) %>%
      distinct(fterm_id, fterm_name) %>%
      ungroup()
    
    # Calculate summary statistics for ORA
    ORA_logFC_summary <- ORA.df %>%
      merge(., term_to_gene.df, by = "entity_id", all.x = TRUE) %>%
      group_by(strain, fterm_id) %>%
      summarise(mean_logFC = mean(logFC), median_logFC = median(logFC)) %>%
      ungroup() %>%
      dplyr::select(-strain)
    
    # Perform ORA
    ORA <- enricher(
      gene = glist.ORA,
      TERM2GENE = term_to_gene.df,
      TERM2NAME = term_to_name.df,
      universe = bglist.ORA,
      qvalueCutoff = 1,
      minGSSize = 5,
      maxGSSize = length(bglist.ORA) / 2,
      pvalueCutoff = 1,
      pAdjustMethod = "fdr"
    )
    
    # Store ORA results
    omics_list_ORA[[my_strain]] <- ORA
    omics_list_ORA_summary[[my_strain]] <- ORA %>%
      as.data.frame() %>%
      mutate(strain = my_strain) %>%
      mutate(experiment = my_omics) %>%
      merge(., ORA_logFC_summary, by.x = "ID", by.y = "fterm_id")
    
    # GSEA Analysis
    GSEA.df <- all_DE.res %>%
      filter(is_species_core %in% is_core_accessory) %>%
      filter(strain == my_strain) %>%
      filter(experiment == my_omics) %>%
      distinct(entity_id, .keep_all = TRUE)
    
    glist.GSEA <- GSEA.df$logFC
    names(glist.GSEA) <- GSEA.df$entity_id
    glist.GSEA <- sort(glist.GSEA, decreasing = TRUE)
    
    GSEA <- GSEA(
      geneList = glist.GSEA,
      TERM2GENE = term_to_gene.df,
      TERM2NAME = term_to_name.df,
      minGSSize = 5,
      maxGSSize = length(bglist.ORA) / 2,
      pvalueCutoff = 1,
      pAdjustMethod = "fdr",
      nPermSimple = 100000,  # Increase the number of permutations
      eps = 0  # Allow more precise p-value estimation
    )
    
    # Store GSEA results
    omics_list_GSEA[[my_strain]] <- GSEA
    omics_list_GSEA_summary[[my_strain]] <- GSEA %>%
      as.data.frame() %>%
      mutate(strain = my_strain) %>%
      mutate(experiment = my_omics) %>%
      merge(., term_to_name.df, by.x = "ID", by.y = "fterm_id", all.x = TRUE)
  }
  
  # Save all results for this omics
  results_list[[my_omics]] <- list(
    ORA = omics_list_ORA,
    ORA_summary = omics_list_ORA_summary,
    GSEA = omics_list_GSEA,
    GSEA_summary = omics_list_GSEA_summary
  )
}
```

### Access results for a specific omics/strain
```{r}
# Access results for a specific omics
# results_list[["Transcriptomics RG"]]

# View ORA summary for BPH2769 (Transcriptome)
head(results_list[["Transcriptomics RG"]]$ORA_summary$AJ218, 5)
```

## Save
```{r}
#saveRDS(results_list, file = "/Users/wmujchariyak/Desktop/ORA_GSEA_list_Kleb.rds")
```


