---
title: "Extract gene list from each node"
author: "Warasinee Mujchariyakul"
output: html_document
date: "2025-06-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load R packages
```{r}
library(clusterProfiler)
library(tidyverse)
library(dplyr)
```

# Import Annotation Data 
```{r}
# Gene Annotation
geneAnno <- read.table("/Users/wmujchariyak/Desktop/Strep_gene_anno.tsv", header = TRUE)

# Pathway Annotation
pathwayAnno_GO <- read.table("/Users/wmujchariyak/Desktop/Strep_GO_anno.tsv", header = TRUE)
pathwayAnno_KEGG <- read.table("/Users/wmujchariyak/Desktop/Strep_KEGG_anno.tsv", header = TRUE)
```

# Import Node Data 
```{r}
node_data <- read.table("/Users/wmujchariyak/Desktop/Strep_node_table.tsv", header = TRUE) %>% mutate(Experiment = "Transcriptome", PEA = "GSEA")
```

# Import Pathway Enrichment Outputs (ORA/GSEA)
```{r}
PEA_output <- readRDS("/Users/wmujchariyak/Desktop/Strep_Trans_GSEA_list.rds")
```

## Set parameters 
```{r}
## Number of strains
node_data_n5 <- node_data %>% filter(nb_strain_with_node == 5)

## Add ID (use pathwayAnno_KEGG because our node data contain KEGG pathways)
node_data_n5_ID <- node_data_n5 %>% left_join(pathwayAnno_KEGG, by = "name")
```

## Subset sig GSEA 
```{r}
Trans.5448.GSEA.sig <- clusterProfiler::filter(PEA_output[["5448"]], p.adjust < 0.05)
Trans.HKU419.GSEA.sig <- clusterProfiler::filter(PEA_output[["HKU419"]], p.adjust < 0.05)
Trans.PS003.GSEA.sig <- clusterProfiler::filter(PEA_output[["PS003"]], p.adjust < 0.05)
Trans.PS006.GSEA.sig <- clusterProfiler::filter(PEA_output[["PS006"]], p.adjust < 0.05)
Trans.SP444.GSEA.sig <- clusterProfiler::filter(PEA_output[["SP444"]], p.adjust < 0.05)

Trans.5448.GSEA.sig_2 <- Trans.5448.GSEA.sig@result %>% dplyr::select(ID, core_enrichment) %>% rename("5448"=core_enrichment) %>% mutate(PEA ="GSEA") 
Trans.HKU419.GSEA.sig_2 <- Trans.HKU419.GSEA.sig@result %>% dplyr::select(ID, core_enrichment) %>% rename(HKU419=core_enrichment)  %>% mutate(PEA ="GSEA") 
Trans.PS003.GSEA.sig_2 <- Trans.PS003.GSEA.sig@result %>% dplyr::select(ID, core_enrichment) %>% rename(PS003=core_enrichment)  %>% mutate(PEA ="GSEA") 
Trans.PS006.GSEA.sig_2 <- Trans.PS006.GSEA.sig@result %>% dplyr::select(ID, core_enrichment) %>% rename(PS006=core_enrichment)  %>% mutate(PEA ="GSEA") 
Trans.SP444.GSEA.sig_2 <- Trans.SP444.GSEA.sig@result %>% dplyr::select(ID, core_enrichment) %>% rename(SP444=core_enrichment)  %>% mutate(PEA ="GSEA") 

## Merge all five table by reduce(left_join)
# List of data frames
Trans_sig_PEA_list <- list(Trans.5448.GSEA.sig_2, Trans.HKU419.GSEA.sig_2, Trans.PS003.GSEA.sig_2, Trans.PS006.GSEA.sig_2, Trans.SP444.GSEA.sig_2)

# Merge all data frames using reduce(left_join)
merged_Trans_sig_PEA_list <- purrr::reduce(Trans_sig_PEA_list, left_join, by = c("ID", "PEA")) %>% mutate(Experiment = "Transcriptome")

node_data_n5_ID_gene_list <- node_data_n5_ID %>% left_join(merged_Trans_sig_PEA_list, by = c("ID", "PEA", "Experiment"))
```


## Extract core_entitiy_id 
```{r}

# DataFrame1: original data
df1_n5 <- node_data_n5_ID_gene_list

# DataFrame2: Mapping Table 
df2_map <- geneAnno

###########################
### Replace entity_id in df1_5 with core_entity_id

# Create a named vector for ID mapping
id_map <- setNames(df2_map$core_entity_id, df2_map$entity_id)

# Split the Gene_ID strings, replace old IDs with new ones, and recombine
df1_n5[["5448"]] <- sapply(strsplit(as.character(df1_n5[["5448"]]), "/"), 
                      function(ids) {
                        new_ids <- id_map[ids]
                        paste(new_ids, collapse = "/")
                      })

# Try with other columns 
df1_n5$HKU419 <- sapply(strsplit(as.character(df1_n5$HKU419), "/"), 
                      function(ids) {
                        new_ids <- id_map[ids]
                        paste(new_ids, collapse = "/")
                      })

df1_n5$PS003 <- sapply(strsplit(as.character(df1_n5$PS003), "/"), 
                      function(ids) {
                        new_ids <- id_map[ids]
                        paste(new_ids, collapse = "/")
                      })

df1_n5$PS006 <- sapply(strsplit(as.character(df1_n5$PS006), "/"), 
                      function(ids) {
                        new_ids <- id_map[ids]
                        paste(new_ids, collapse = "/")
                      })

df1_n5$SP444 <- sapply(strsplit(as.character(df1_n5$SP444), "/"), 
                      function(ids) {
                        new_ids <- id_map[ids]
                        paste(new_ids, collapse = "/")
                      })
```



## Extract gene name 
```{r}
# DataFrame1: original data
df1_n5_name <- node_data_n5_ID_gene_list

# DataFrame2: Mapping Table 
df2_map <- geneAnno

###########################
### Replace entity_id in df1_5 with core_consensus_annotation

# Create a named vector for ID mapping
id_map2 <- setNames(df2_map$core_consensus_annotation, df2_map$entity_id)

# Split the Gene_ID strings, replace old IDs with new ones, and recombine
df1_n5_name[["5448"]] <- sapply(strsplit(as.character(df1_n5_name[["5448"]]), "/"), 
                      function(ids) {
                        new_ids <- id_map2[ids]
                        paste(new_ids, collapse = "/")
                      })

# Try with other columns 
df1_n5_name$HKU419 <- sapply(strsplit(as.character(df1_n5_name$HKU419), "/"), 
                      function(ids) {
                        new_ids <- id_map2[ids]
                        paste(new_ids, collapse = "/")
                      })

df1_n5_name$PS003 <- sapply(strsplit(as.character(df1_n5_name$PS003), "/"), 
                      function(ids) {
                        new_ids <- id_map2[ids]
                        paste(new_ids, collapse = "/")
                      })

df1_n5_name$PS006 <- sapply(strsplit(as.character(df1_n5_name$PS006), "/"), 
                      function(ids) {
                        new_ids <- id_map2[ids]
                        paste(new_ids, collapse = "/")
                      })

df1_n5_name$SP444 <- sapply(strsplit(as.character(df1_n5_name$SP444), "/"), 
                      function(ids) {
                        new_ids <- id_map2[ids]
                        paste(new_ids, collapse = "/")
                      })
```

# View dataframe results 
```{r}
head(df1_n5, n =5)
head(df1_n5_name, n =5)
```

